from collections import Counter


class Solution:
    """
        You are given two strings s and t.

        String t is generated by random shuffling string s and then add one more letter at a random position.

        Return the letter that was added to t.

        Example 1:

        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.
        Example 2:

        Input: s = "", t = "y"
        Output: "y"

        Constraints:

        0 <= s.length <= 1000
        t.length == s.length + 1
        s and t consist of lowercase English letters.
    """
    def findTheDifference1(self, s: str, t: str) -> str:
        if not s:
            return t
        sList = sorted(s)
        tList = sorted(t)
        for i in range(len(sList)):
            if sList[i] != tList[i]:
                return tList[i]
        return tList[-1]

    def findTheDifference(self, s: str, t: str) -> str:
        sDict = Counter(s)
        for ch in t:
            if ch not in sDict or sDict[ch] == 0:
                return ch
            sDict[ch] -= 1
        return t[-1]
